classDiagram
    class Entity
    class Continuant
    class IndependentContinuant
    class MaterialEntity
    class Object
    class ObjectAggregate
    class GDC
    class InformationContentEntity
    class SDC
    class Quality
    class RealizableEntity
    class Role
    class Function
    class Occurrent
    class Process
    class Infrastructure
    class Pipeline
    class Refinery
    class OffshorePlatform
    class Wellhead
    class Equipment
    class Pump
    class Valve
    class Compressor
    class Sensor
    class PressureSensor
    class TemperatureSensor
    class VibrationSensor
    class PLC
    class Substance
    class Petroleum
    class NaturalGas
    class Water
    class OperatorRole
    class SafetyRole
    class MaintenanceRole
    class PumpingFunction
    class RefiningFunction
    class SensingFunction
    class IndustrialProcess
    class ExtractionProcess
    class RefiningProcess
    class TransportProcess
    class MaintenanceProcess
    class SensorData
    class SafetyProtocol
    class LimitBreachEvent
    class FailureRisk
    Entity <|-- Continuant
    Continuant <|-- IndependentContinuant
    IndependentContinuant <|-- MaterialEntity
    MaterialEntity <|-- Object
    MaterialEntity <|-- ObjectAggregate
    Continuant <|-- GDC
    GDC <|-- InformationContentEntity
    Continuant <|-- SDC
    SDC <|-- Quality
    SDC <|-- RealizableEntity
    RealizableEntity <|-- Role
    RealizableEntity <|-- Function
    Entity <|-- Occurrent
    Occurrent <|-- Process
    Object <|-- Infrastructure
    Infrastructure <|-- Pipeline
    Infrastructure <|-- Refinery
    Infrastructure <|-- OffshorePlatform
    Infrastructure <|-- Wellhead
    Object <|-- Equipment
    Equipment <|-- Pump
    Equipment <|-- Valve
    Equipment <|-- Compressor
    Equipment <|-- Sensor
    Sensor <|-- PressureSensor
    Sensor <|-- TemperatureSensor
    Sensor <|-- VibrationSensor
    Equipment <|-- PLC
    MaterialEntity <|-- Substance
    Substance <|-- Petroleum
    Substance <|-- NaturalGas
    Substance <|-- Water
    Role <|-- OperatorRole
    Role <|-- SafetyRole
    Role <|-- MaintenanceRole
    Function <|-- PumpingFunction
    Function <|-- RefiningFunction
    Function <|-- SensingFunction
    Process <|-- IndustrialProcess
    IndustrialProcess <|-- ExtractionProcess
    IndustrialProcess <|-- RefiningProcess
    IndustrialProcess <|-- TransportProcess
    IndustrialProcess <|-- MaintenanceProcess
    InformationContentEntity <|-- SensorData
    InformationContentEntity <|-- SafetyProtocol
    InformationContentEntity <|-- LimitBreachEvent
    InformationContentEntity <|-- FailureRisk
    MaterialEntity : +Integer has_pressure
    MaterialEntity : +Integer has_temperature
    MaterialEntity : +Integer has_vibration_level
    Valve : +Integer valve_position
    Equipment : +Boolean is_active
    Pipeline : +Integer flow_rate
