classDiagram
    class Entity
    class Continuant
    class IndependentContinuant
    class MaterialEntity
    class Object
    class Occurrent
    class Process
    class Role
    class Function
    class InformationContentEntity
    class OrganizationUnit
    class EngineeringUnit
    class SalesUnit
    class CustomerSuccessUnit
    class CloudOperationsUnit
    class Product
    class HiveMQBroker
    class HiveMQEdge
    class HiveMQCloud
    class HiveMQExtension
    class Customer
    class AutomotiveCustomer
    class EnergyCustomer
    class ManufacturingCustomer
    class LogisticsCustomer
    class Environment
    class OnPremisesEnvironment
    class PublicCloudEnvironment
    class HybridEnvironment
    class BusinessProcess
    class SoftwareDesignProcess
    class SalesCycleProcess
    class CustomerOnboardingProcess
    class IncidentResolutionProcess
    class CloudProvisioningProcess
    class Contract
    class SLA
    class FeatureRequest
    class SupportTicket
    class ExecutiveRole
    Entity <|-- Continuant
    Continuant <|-- IndependentContinuant
    IndependentContinuant <|-- MaterialEntity
    MaterialEntity <|-- Object
    Entity <|-- Occurrent
    Occurrent <|-- Process
    Continuant <|-- Role
    Continuant <|-- Function
    Continuant <|-- InformationContentEntity
    Object <|-- OrganizationUnit
    OrganizationUnit <|-- EngineeringUnit
    OrganizationUnit <|-- SalesUnit
    OrganizationUnit <|-- CustomerSuccessUnit
    OrganizationUnit <|-- CloudOperationsUnit
    Object <|-- Product
    Product <|-- HiveMQBroker
    Product <|-- HiveMQEdge
    Product <|-- HiveMQCloud
    Product <|-- HiveMQExtension
    Object <|-- Customer
    Customer <|-- AutomotiveCustomer
    Customer <|-- EnergyCustomer
    Customer <|-- ManufacturingCustomer
    Customer <|-- LogisticsCustomer
    Object <|-- Environment
    Environment <|-- OnPremisesEnvironment
    Environment <|-- PublicCloudEnvironment
    Environment <|-- HybridEnvironment
    Process <|-- BusinessProcess
    BusinessProcess <|-- SoftwareDesignProcess
    BusinessProcess <|-- SalesCycleProcess
    BusinessProcess <|-- CustomerOnboardingProcess
    BusinessProcess <|-- IncidentResolutionProcess
    BusinessProcess <|-- CloudProvisioningProcess
    InformationContentEntity <|-- Contract
    InformationContentEntity <|-- SLA
    InformationContentEntity <|-- FeatureRequest
    InformationContentEntity <|-- SupportTicket
    Role <|-- ExecutiveRole
    Contract : +Integer contract_value
    SLA : +Integer sla_uptime_target
    Customer : +Integer customer_satisfaction
    Product : +Boolean is_deployed
